FROM golang:1.22-alpine

# Устанавливаем Node.js и npm (в alpine это делается одной командой)
RUN apk add --no-cache nodejs npm

WORKDIR /app

# Открываем порты: 3000 для React (Vite) и 8080 для Go
EXPOSE 5173 8080

# Мы не копируем код здесь! Мы сделаем это при запуске.
CMD ["sh"]