services:
  front:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app 
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true
    working_dir: /app/client
    command: sh -c "npm run dev -- --host"

  back:
    build:
     context: ./server
     dockerfile: Dockerfile.dev
    volumes:
     - .:/app
    ports: 
     - "8080:8080"
    tty: true
    stdin_open: true
    working_dir: /app/server
    command: sh -c "go mod download && go run main.go"
